### ISSUE TITLE
About pre-training hardware

### ISSUE THREAD

**Issue by tomchen-ctj** [TengdaHan/TemporalAlignNet#2]
Hi, 

Thank you for your solid work and code releases.
May I ask how many GPUs are used in the basic TAN pre-training? (Sorry if I missed that description in your paper)

Thanks!

**Comment by TengdaHan** [comment]
Hi, the basic TAN pre-training is on frozen visual features, so it requires fewer GPUs.
I mostly use only one GPU (but with 48gb gpu-memory) for one experiment.

**Comment by tomchen-ctj** [comment]
I see, thank you!
