### ISSUE TITLE
video timestamps

### ISSUE THREAD

**Issue by lucas-ventura** [TengdaHan/TemporalAlignNet#3]
Hey, thank you for the amazing work!

How should we interpret the video timestamps? 

There are many cases where the timestamp is off by a lot. For example, in the [oatmgMKmbmA](https://youtu.be/oatmgMKmbmA) video:
`oatmgMKmbmA,5,my favorite around the birthday cake` timestamp at 5s but if we listen to the video it only happens after second 25.
`oatmgMKmbmA,16,so the bakery we usually learn on whipped cream and then graduate to buttercream` happens at second 20 (before the previous row).

Any help regarding this topic will be appreciated. Thanks!

**Comment by TengdaHan** [comment]
Hi, sorry for the late reply. 
I think you mean the timestamps from the HTM-AA dataset here: https://github.com/TengdaHan/TemporalAlignNet/tree/main/htm_aa 
This is the **auto-aligned** version of the HowTo100M dataset, and the timestamps are predicted by the model as "the most corresponding video timestamp for the given text". Our model gives the "centre time" of the text.

For example, in second `20` the instructor says the sentence `... whipped cream and then graduate to buttercream`, but our model predicts the second `16` is the MOST corresponding video scene to this text. Our model learns to do this in a self-supervised way, so there is still some noise (visual and text might not correspond perfectly).

So the annotation is not the original ASR timestamps. There is usually a temporal shift.

PS: we do plan to release the original ASR timestamps for the HowTo100M dataset (before the auto-alignment) in the next few weeks.

**Comment by lucas-ventura** [comment]
Great, thank you for your response!
